---
title: "Project 2 -- Problem Set 1: Cross Sectional Data Analysis"
format: 
  html:
    theme: zephyr
---
## Problem Set Overview

This problem set is designed to help you start your [Project 2](../week_04/project_2.qmd) analysis by gaining familiarity with the convenience store datasets provided. You will perform exploratory data analysis (EDA) and begin initial clustering to identify patterns in your data.

## Data for this Problem Set

You will use the following datasets:

**<a  href="../inputs/shopper_info.csv" download>shopper_info.csv</a>**: This file contains transaction-level data, including information about the shopper, the store where the purchase was made, the products purchased (identified by GTIN), and the quantities and prices.

**<a  href="../inputs/gtin.csv" download>gtin.csv</a>**: This file provides additional details about the products, which can be linked to the shopper_info.csv file using the GTIN (Global Trade Item Number) variable.

**<a  href="../inputs/store_info.csv" download>store_info.csv</a>**: This file includes information about the stores, such as location, size, and other characteristics, which can be linked to the shopper_info.csv file using the store_id variable.

Review the [Lab Notes for Week 09](lab_02_week_01.html) for a codebook describing the three data files.

## Part 1: Specify Your Research Question

1. Review [Project 2 Instructions](../week_04/project_2.qmd). 

2. Clearly outline the segmentation and question you will analyze:

- Specify **one segmentation area** you have chosen for the analysis (customers, stores, or products).

- Clearly articulate your research question.

- Explain why answering this question is valuable and specify who will benefit from the insights (e.g., business executives, store managers, marketers).

::: {.callout-note}

## Three Options for This Project

**Customer Segmentation:**

- Example: Can we identify customer groups based on product preferences, purchase frequency, or spending level?

**Store Segmentation:**

- Example: Are there distinct types of stores based on sales performance, product diversity, or customer base?

**Product Segmentation:**

- Example: Can we group products based on shared characteristics (e.g., price, package size, brand, category)?

:::

## Part 2: R

Complete the following steps using the provided datasets (shopper_info.csv, gtin.csv, and store_info.csv):

2. Depending on the segment you have chosen, merge the relevant datasets appropriately - these might be two or all three datasets - and clean the dataset. Clearly document and justify all processing steps, such as:

- Handling missing data

- Removing outliers

- Dropping observations

- Transforming or aggregating variables

- Creating new variables

3. Using your merged and cleaned dataset, generate a table of summary statistics. The table should include at least: variable names, mean (average), standard deviation, min, and max.

4. Write a narrative for explaining the steps you took to merge and clean your data and providing an interpretation of your data. Describe your data so that readers understand what is measured.

5. Conduct an *initial* K-means clustering analysis:

- Select relevant numeric variables based on your segmentation choice. These variables may be ones that you had to create in answering question #2.

- Perform cluster analysis using different cluster sizes (e.g., 3-5 clusters) and explain your choice clearly.

Note: You will come back to this R script in problem set 2.

6. Write a narrative explaining your initial clustering results, including what the clusters indicate about the dataset.

## How to Submit

Create a new page on your Google Site titled `Project 2 Problem Set 1`. *Remember: Add this as a **new page** to your existing website. Do not create a new website.*

This assignment has three components:

1. Your Research Question

- On your webpage for this assignment, describe the segmentations you have chosen, the research question, and who will benefit from the insights.

2. R code 

- Comment each step of your code, including summary statistics, cluster results, and any relevant visualizations (e.g., the elbow and silhouette plots).

3. Your Narrative

- On your webpage for this assignment, write a narrative that corresponds with questions 4 and 6. 

Submit the link to your webpage on Canvas. 

::: {.callout-important}

## Reminder: How to Use "Compile Report" Option in R

*Going going forward, please use the "Compile Report" process to submit your R code. We will no longer use "sink-source-sink".*

{{< video https://youtu.be/B2AchbhnFTo aspect-ratio="16x9" >}}

- Under the File menu, select **Compile Report...**
- The default under "Report output format" is HTML. 
- Select **Compile**
- Along the tool bar, select **Open in Browser**
- Hover your cursor over white space and **right click**.
- Select **View page source**.
- A new screen will appear with HTML code. (Don't worry, this might look like gibberish, but it's not!)
- Using your keyboard, click **`CTRL`+`A`**. This will highlight all of the HTML code.
- While the HTML code is highlighted, **right click** and select **Copy**.
- Go to your Google website. 
- Similar to as you would embed your Tableau visualization, select **Embed** under Insert.
- Then, select **Embed code**.
- Paste your embed code from your clipboard by either right-clicking and selecting **Paste** or `CTRL`+`V`.
- Select **Next**.
- **Resize** the image of your R script by expanding the window to fit the entire script.  

Following these steps will display your entire code and output without truncation. 

:::