---
title: "Problem Set 1: Introduction to R and Tableau"
format: 
  html:
    theme: zephyr
---

## Part 1: R

<!-- Link to website -->
1. Create a variable called `myage` and assign it the value of your age.

2. Create a vector called `grades` containing the following values: 88, 92, 75, 99, and 80.

3. Using indexing, print the third element of the `grades` vector to the console.

4. Create a data frame called `student_info` containing the following columns: Name, Age, Major, Absent. The data should be as follows:

```{r,echo=FALSE,results='asis'}
knitr::kable(data.frame(
   Name = c("John", "Emily", "Michael", "Jessica"),
   Age = c(20, 22, 19, 21),
   Major = c("AgBiz", "ENRE", "ENRE", "AgBiz"),
   Absent = c(TRUE, TRUE, FALSE, FALSE)
))

```

5. Download the [Supermarket Sales data](../inputs/supermarket_sales.csv) in csv format to a known location on your machine. The dataset should be called `supermarket_sales.csv`. Using the `setwd()` function, set your working directory to the location where you have a file called `supermarket_sales.csv`

6. Using the `read.csv()` function, read in the file `supermarket_sales.csv` and assign it to an object called `mydata`.

7. Install and load the package `readr`.

8. Write a brief explanation of what you did in steps 1-7 and how it relates to the tutorial we did in class.

## Part 2: Getting Started with Tableau

We will be using two Tableau products in this course (although there are many more - see handout): Tableau Desktop and Tableau Public. Tableau desktop typically requires a paid subscription, but as students (and teachers) we get it for free. Your assignment for this week is to be fully prepared to use these two Tableau products on your personal computer. 

1.  Visit [Tableau Desktop](https://www.tableau.com/products/desktop) and download Tableau Desktop using the 14-day free trial. You can enter your product license key once you receive an email with your academic license. **Take a screenshot of Tableau Desktop open on your computer.** 

2.  Visit [Tableau Public](https://public.tableau.com/app/discover) and create an account. You will use this account to host your data visualizations, which you can then embed on your google site. You will be required to use this to upload homework assignments.

<!--
Connect to the `supermarket_sales.csv` and answer the following questions using information on the `Start Page`, `Data Source Page`, and by opening a new `Worksheet`.

1.  What type of connection did you use to connect to `supermarket_sales.csv`?

2.  What type of data is `supermarket_sales.csv`?

3.  How many sheets are included in `supermarket_sales.csv`?

4.  How many data fields are included in `supermarket_sales.csv`?

5.  What is the role of the variable `City`?

6.  What is the type of the variable `City`?

7.  What is the role of the variable `Total`?

8.  What is the type of the variable `Total`?

9.  Open a new sheet. Drag the variable `Total` to the Rows shelf and the variable `City` to the Columns shelf. Give your sheet a useful title, save your workbook, and publish your workbook to your Tableau Public site. 
-->

## How to Submit

1. **Create a Webpage on Your Google Site:**

- Title the new webpage Problem Set 1.
- This page should include your responses to Part 1 and Part 2 of the problem set.

2. **Include the Following Content:**

- **Part 1:**

  - Display the contents of your log file, which you generated by sourcing your R script. (Refer to the lab instructions for guidance on creating a log file.)
  - Write your answer to Question 8 in paragraph form.

- **Part 2:**

  - Provide evidence that you completed Steps 1 & 2 as described in the problem set.
  - Include a link to your Tableau Public site where your work is published.

3. **Submit the Link to Your Google Site Page:**

- Copy the URL of your Google Site webpage for Problem Set 1.
- Submit this link via Canvas.

<!--You should create a new webpage on your google site titled `Problem Set 1`. This webpage should include your responses to both Parts 1 and Parts 2 of the problem set. Part 1 should display the contents of your log file generated when you source your R script and your answer to question 8 in paragraph form. Review the instructions in the lab to see how to generate the log file. Part 2 should contain your evidence of completing steps 1 & 2 and a link to your Tableau Public site. Submit the link to your google site webpage in Canvas.-->