---
title: "Project 1 -- Problem Set 1: Starting Project 1 and Working with Time Series Data"
format: 
  html:
    theme: zephyr
---

## Overview

The objective of this assignment is to explore time series datasets and become familiar with tools to obtain and visualize time series data. 

## Before you begin

Review the [Project 01 instructions](https://https//csu-arec-330.github.io/materials/unit_01/project/project_1_instructions.html). 

Treat this assignment as the first step of your project—choose time series data that interest you and that you would like to study further. 

**You may work on this assignment with your partner. However, each person will submit the assignment individually. If one person builds the visualizations in Tableau, use their embed code on your Google site.**

## Part 1: R – Acquiring and Preparing Data

The goal of this section is to acquire and modify your data so that it is ready for visualization in Tableau.

### **Instructions:**

1. All computer programs track time numerically relative to an epoch. What is the numeric value of the assignment due date?

2. Use the `tidyquant` package to access the FRED API and download **three time series datasets** relevant to your topic of interest.

3. Use `case_when()` to rename the series to more **descriptive** names.

4. Save your dataset in **.csv format** so that it can be used in Tableau.

**Note:** *If you choose to use an alternative dataset, not from FRED, please get approval from the instructor.*

## Part 2: Tableau – Visualizing and Analyzing Trends

The objective of this section is to explore the data and identify external factors that may have influenced price trends in your dataset. You may need to do some **research** to understand events that impacted your time series.

### **Instructions:**

1. Load the **time series dataset** you prepared in Part 1 into Tableau.

2. Generate a **line chart** showing **monthly prices** for your three selected time series. What is the best way to visualize the three time series? Note: Review the video from [Lab 05](https://csu-arec-330.github.io/materials/unit_01/week_01/lab_01_week_01.html#video-using-tableau-to-visualize-time-series-data) and the lab notes on [creating panes to visualize multiple time series](https://csu-arec-330.github.io/materials/unit_01/week_01/lab_01_week_01.html#creating-panes-to-visualize-mutiple-time-series).

3. Format your chart according to the guidelines for effective visualizations:
     - Adjust the time window (e.g., limit to a time window that helps the audience see differences before and after the event you are highlighting)
     - Use appropriate colors
     - Add a title, axis labels, and annotations
     - Include marker labels and relevant text annotations

4. Write a **narrative** on your Google Site  
   - Create a new webpage titled **“Problem Set 5”**
   - Embed your Tableau visualization
   - Write a short narrative explaining what your visualization highlights and why it is significant. In your narrative, formulate a question that you would like to answer for [Project 01](https://https//csu-arec-330.github.io/materials/unit_01/project/project_1_instructions.html). 
   
## How to Submit

1. **Create a new webpage on your Google site** titled `Problem Set 5`.
2. **Include the following:**
   - **Part 1**: An R script displaying the code used for data acquisition and modification.
   - **Part 2**: Your Tableau visualization and a written narrative.
3. **Publish the page and submit the link** to your Google site webpage in Canvas.