---
title: "Week 1 Handout: Tableau Terminology"
format: 
  html:
    theme: zephyr
---

**Learning Objective**: Define key Tableau terminology

## Tableau Common Types of Data and Data Fields

Tableau terminology consists of general data literacy as well as terminology specific to Tableau. 

### Data Sets
Data sets, databases, or data sources are collections of data. The different types of data sets that are used in Tableau include:

- **Spreadsheets** organize data in a *flat* structure, meaning records are stored as single rows of data. MS Excel and Google Sheets are examples.

- **Relational databases** store data in multiple tables, with each row assigned a unique identifier and with a logical connection between different tables. Users pull data from different tables together using Structured Query Language (SQL). 
- **Cloud data** consists of spreadsheets and relational databases that are stored in the cloud so that on-site servers are not necessary. Amazon Web Services and MS Azure are examples.

- **Spatial files** such as .kml and .shp are also common in Tableau for mapping purposes.

- **Metadata** is a set of data that describes other data. For example data fields (next) are stored as metadata.

### Data Fields

When users *connect* Tableau to databases, Tableau automatically assigns the *data fields* in the data set a *role* and *type*. 

- **Data Fields** are the columns in your data set. They are also known as *variables*. They include a single piece of information for records (rows) in your data sets.

- **Role:** Each data field can have either a Dimension or Measure role.

	- **Dimensions** are *qualitative*. These data fields describe or categorize data. These data fields can be text (*string*) or numerical with integers corresponding to different categories. (e.g. survey data on years of education or annual income often *bins* or *slices* the quantitative data)

	- **Measures** are *quantitative*. These data fields provide measurements and are numerical. These data fields can be used in *calculations*.

- **Type:** String, Integer, Date, Geographic, etc. 

## Data Aggregation

**Data aggregation** refers to how data is combined. The level of **granularity** or **aggregation** in a row of data impacts the questions we can answer with the data and the visualizations we can create. Less aggregate  (or disaggregate or more granular) data will have more observations that aggregated data. For example, data on average corn yields by state each year (Table 1) are less aggregate, and consist of more observations, than average corn yields for the entire U.S. by year (Table 2). More aggregated data combine the less aggregated data in some logical and useful way. In the corn yield example, the data are aggregated by taking the average yield across all states within the year. However, you might also take the maximum, minimum, or median values (or a variety of other statistics). 

| State      | Year | Yield (bu/ac) |
| ---------- | ---- | ------------- |
| Oregon     | 2019 | 237           |
| Washington | 2019 | 237           |
| Arizona    | 2019 | 231           |
[Table 1. Average U.S. Corn Yields by State (Less Aggregate/More Granular)]

| Year | Yield (bu/ac) |
| ---- | ------------- |
| 2019 | 139           |
| 2018 | 137           |
| 2017 | 129           |
[Average U.S. Corn Yields (More Aggregate/Less Granular)]

- What types of analyses might you be able to do with the state-level (*more* granular) data that you could not with the national-level (*less* granular) data above?

	- State-level data would enable us to explore some potential reasons for differences in yields that can be explained with geographic and temporal variation, for example: 

		1. How does weather influence yields?

		2. How do soil conditions influence yields?

		3. How do state policies or funding influence yields?

		4. And more!

- Could these data be made even more granular? How?

	1. County-level 

	2. Farm-level

	3. Field-level 

	4. Month-level

	5. Day-level

	6. And more!

**Data Aggregation in Tableau:** Once you *connect* Tableau to a dataset, there are several ways to *aggregate* your data. By default, Tableau likes to sum *measures* with common *dimensions*, but you can also construct averages, percentages, and much, much more!

**Wide Versus Long Formatted Data**

| Year | Oregon | Washington | Arizona |
| ---- | ------ | ---------- | ------- |
| 2019 | 237    | 237        | 231     |
[Average U.S. Corn Yields by State (Less Aggregated/More Granular) Wide Format]

**Note that Tableau prefers long-formatted data** — once the data is loaded into Tableau in long format you can perform aggregations.

**Note that most regression analyses require wide-formatted data** — to accomplish this we can reshape our data in R to prepare it for analysis.
