# Site settings
title: AREC 330 Course Website
subtitle: Home Page
description: |
    Welcome to the course webpage for AREC 330 -- Data-Driven Decision Making in Agricultural and Resource Economics. The world generates [2.5 quintillion bytes](https://financesonline.com/how-much-data-is-created-every-day/#:~:text=Every%20day%20Big%20Data%20statistics,(2021%2C%20February%209).) of data each day. One of the key modern business challenges is transforming that data into actionable insights that improve decision making (i.e., data-driven decision making). Transforming data into information is not magic. It requires understanding the decision problem, organizing and processing data, analyzing data, and finally presenting information. This course will introduce you to this process of transforming data into actionable insights and build a core set of competencies with two commonly used software: R and Tableau. Since we only have 16 weeks, the most important lesson you will learn in this class is how to teach yourself what you need to know in the future. You will learn these skills by completing the three group projects over the semester.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://csu-arec-330.github.io" # the base hostname & protocol for your site
syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/syllabus-example/svm-rmarkdown-syllabus-example.pdf"
githubdir: "csu-arec-330/csu-arec-330.github.io"

# Author/user information
email: alexandra.e.hill@colostate.edu
#twitter_username: stevenvmiller
#github_username:  svmiller
authorurl: "https://alexandraehill.github.io"
address: |
    Department of Agricultural and Resource Economics
    Colorado State University | Nutrien 213


# Build settings
markdown: kramdown

# module setup
# Collections for website data
collections:
  modules:
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
