# Site settings
title: Course Website
subtitle: AREC 705
description: |
    Welcome to the course webpage for AREC 705 -- Agricultural Production and Technological Change. Throughout this course we will be studying and applying modern theoretical and empirical approaches to understand agricultural producer decision-making, including decision-making over multiple stages and under risk, the generation, adoption, and diffusion of agricultural technologies, measurements of technical efficiency and productivity, and advanced models of agricultural markets. My goal in this course is to equip you with an array of theoretical and empirical modeling tools that will enable you to conduct research related to and relevant for agricultural producers. On this website you will find the course syllabus, weekly reading assignments, lecture slides and notes, and a link to the google classroom you will use to submit assignments. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://csu-arec-705.github.io" # the base hostname & protocol for your site
syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/syllabus-example/svm-rmarkdown-syllabus-example.pdf"
githubdir: "csu-arec-705/csu-arec-705.github.io"

# Author/user information
email: alexandra.e.hill@colostate.edu
#twitter_username: stevenvmiller
#github_username:  svmiller
authorurl: "https://alexandraehill.github.io"
address: |
    Department of Agricultural and Resource Economics
    Colorado State University | Nutrien 213


# Build settings
markdown: kramdown

# module setup
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
