---
title: "Supermarket Sales Data Overview"
format: html
---

### Description
This supermarket dataset is a collection of data that provides information about the transactions that took place in a supermarket chain. The dataset includes sales observations from 3 different branches over a 3 month period. This dataset includes information such as the date and time of the transaction, the products that were purchased, the price of each product, the total amount spent on the transaction, and other relevant details.

We will use this dataset to perform exploratory data analysis and gain insights into the behavior of the supermarket customers. We will use this dataset to identify trends and patterns in customer behavior to develop marketing and advertising strategies.

Overall, this supermarket dataset can be a valuable tool for understanding and predicting the behavior of supermarket customers, and for making data-driven decisions that can improve the performance of a supermarket business.

This dataset is available from kaggle: [https://www.kaggle.com/datasets/aungpyaeap/supermarket-sales](https://www.kaggle.com/datasets/aungpyaeap/supermarket-sales)


### Data Dictionary

The table below provides an overview of the dataset [supermarket_sales.csv](../inputs/supermarket_sales.csv). 

| Variable Name           | Description                                                                                                                                                    |
| ----------------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Invoice ID              | Computer generated sales slip invoice identification number                                                                                                    |
| Branch                  | Branch of supercenter (3 branches are available identified by A, B and C).                                                                                     |
| City                    | Location of supercenter                                                                                                                                        |
| Customer                | Type of customers, recorded by Members for customers using member card and Normal for without member card.                                                     |
| Gender                  | Gender of customer                                                                                                                                             |
| Product line            | General item categorization groups - Electronic accessories, Fashion accessories, Food and beverages, Health and beauty, Home and lifestyle, Sports and travel |
| Unit Price              | Price of each product in $                                                                                                                                     |
| Quantity                | Number of units purchased by customer                                                                                                                       |
| Tax                     | 5% tax fee for customer buying                                                                                                                                 |
| Total                   | Total price including tax                                                                                                                                      |
| Date                    | Date of purchase (Record available from January 2019 to March 2019)                                                                                            |
| Time                    | Purchase time (10am to 9pm)                                                                                                                                    |
| Payment                 | Payment used by customer for purchase, 3 methods are available – Cash, Credit card and Ewallet                                                                 |
| COGS                    | Cost of goods sold                                                                                                                                             |
| Gross margin percentage | Gross margin percentage                                                                                                                                        |
| Gross income            | Gross income                                                                                                                                                   |
| Rating                  | Customer stratification rating on their overall shopping experience (On a scale from 1 to 10)                                                                  |
