---
title: "Unit 3: Final Project and Presentations"
format: 
  html:
    theme: zephyr
---

## Overview
<!--
The goal of this project is for you to gain experience with fixed-effects panel regression with an emphasis on causal inference. This is also a chance to showcase your creativity and analytical skills. Create something that you are proud to show others.
-->

The goal of this project is for you to apply panel data analysis that we have covered in the course to answer a real world question. This is also a chance to showcase your creativity and analytic skills. Create something that you are proud to show others.

[**Rubric**](project_3_rubric.html)


### The Question

**The question** Choose one of the treatment or exposure datasets and find an outcome to evaluate.  You are posing some form of the question: What is the impact of $x$ (treatment or exposure) on some outcome $y$?

### The Data

You are given the treatment or exposure dataset. You are responsible for collecting additional data needed to answer this question. First, you need to identify data on the outcome $y$. Second, you need to identify data on any controls that you may need (e.g., weather).  Including control variables in the regression explains a portion of the variation in your data leaving your variable of interest to explain the remaining variation. You are responsible for merging or joining your datasets. This means that you must identify the common unit of analysis in each of your datasets and aggregate data if necessary.

[Additional Datasets](https://colostate-my.sharepoint.com/:f:/g/personal/jbayham_colostate_edu/EsuPJcqiDPZFu0qJ-JONVLcB1gnp08EAm2LuTPAHVz2yqA?e=IsLJkA)


### The Analysis

We expect you to use fixed-effects regression to answer your proposed question. The only strict requirements are: 

1. Present summary statistics of your data. Many of the tabular or data visualization techniques covered in previous units apply to panel data.  You should make clear the number of units and time periods in your dataset. 

2. Perform a fixed-effects regression.

3. Explain your analysis. Is your analysis designed to estimate a treatment effect (of a policy that is present or not) or the marginal effect of an exposure (a continuous variable). You should clearly explain how the analysis helps to answer your research question.

4. Discuss any assumptions you made in your analysis and identify limitations.

5. Present and interpret your results. Use your analysis to clearly answer your research question and tell the audience what to do with the information provided. Provide interpretations of regression results (treatment effect or marginal effect). Use appropriate visualizations to communicate results.

### The Presentation (80 points)

**Overall presentation expectations:** (20 points total)

Your presentations should be 6-9 minutes long. (5 points)

Your presentation should be engaging, follow a logical structure, and should tell a cohesive story that answers your stated question. (5 points)

Your visualizations should be well formatted and appropriate for your analysis/presentation (10 points)

**Presentation Introduction, Background, and Question:** (15 points total)

You should begin your presentation with the following: (5 points)

- Who are you? (what business, organization, etc. wants an answer to your question) 

- Who is your audience? (business executive team, policy makers, consumers?) 

You should then: 

- Give us any relevant background info that is necessary to understanding your question (5 points)

- State your question (5 points)

**Presentation Data and Analysis:** (35 points total)

Data: 

- Describe where your data is from, any modifications to the original data, and how you combined disparate data into a single dataset (10 points)

- Provide summary statistics and visualizations (5 points, see step 1 under `Analysis` above)

Analysis:

- What assumptions did you make in your analysis?  What are limitations to your analysis? (10 points, see step 3 under `Analysis` above)

- Plot AND describe your analysis. (10 points)

**Presentation Discussion/Conclusion:** (10 points total)

- How did you use your analysis to answer your question? What is the answer to your question?

- What are the key take-aways for your intended audience?


### The Write-up/Online Submission (40 points)

You and your partner should also produce a written version of this analysis to post on your website. This should include all of the above components that went into your presentation (think of this as the report that you give to your audience to accompany your presentation) in addition to your R code. The written portion of the assignment is due later so that you can incorporate feedback that you receive during the oral presentation in class.

Because much of the presentation grade is tied to the content of your report, grading for the report will be based on: 

1. Is your code correct and well-explained (use comments to explain what you do at each step!)? Produce an R log.txt file using the `sink()` command and include it as an appendix to your write up. (15 points)

2. Is your report readable and useful? We will not assess the quality of your research question, but we will assess whether your report is something you could hand out to your intended audience and have them understand what you did, why you did it, and what they should do with the information. (10 points)

3. Does your report adequately address the feedback provided after your presentation? We will assess whether and to what extent you incorporated our suggestions. (10 points)

3. Organization, formatting and structure. Is your report organized, presented in a logical order, with appropriate integration of writing, analysis, and code? (5 points)

### Peer Evaluation (15 points)

Each group will be required to provide feedback for three other groups in the class. This feedback process is an essential component of the project, as it encourages constructive criticism and fosters a collaborative learning environment. To facilitate this, each group will complete a Google Form designed specifically for peer evaluations.

Instructions:

1. **Complete the Google Form:** You must answer every question on the Google Form. The form is structured to cover various aspects of the presentations you will evaluate.

2. **Fair Scoring:** You cannot assign full scores in every category for each group. Be thoughtful and provide a balanced evaluation that reflects the strengths and areas for improvement in each presentation.

3. **Be Respectful:** It's important to be respectful and constructive in your comments.

4. **Impact on Grades:** The peer feedback you provide will not be factored into the group's final grade on the presentation. The purpose of this exercise is to give you an opportunity to critically engage with your peers' work and to offer them valuable insights from an outsider's perspective.

A link to the Google Form is also available on Canvas and must be completed by the due date. Please ensure that you dedicate enough time to watch each assigned presentation thoroughly before completing the evaluation form.

Your participation in the peer evaluation process is highly valued and contributes significantly to the learning experience in this course.

