---
title: "Project 2 -- Problem Set 3: Cross Sectional Data Analysis"
format: 
  html:
    theme: zephyr
---
## Problem Set Overview

This problem set is designed to apply both clustering and spatial data analysis.
<!--
## Part 1: Spatial data in R -- DO NOT DO PART 1!!

1. Use one of your project datasets that contains spatial information (or find a new one). Convert it to a spatially aware `sf` object.

2. Perform a spatial intersection associating data from another source with your data. 
-->

## Part 1: R

1. Using your project datasets, perform a K-means cluster analysis as appropriate for your research question or objective. Explain why you clustered on the dimensions you chose and what the clusters tell you. 

2. Summarize the variables you included in your cluster analysis for each cluster. Discuss the results, including any notable differences between the variables across clusters. 

3. Export a dataset that includes all variables you used in your cluster analysis, as well as your clusters. Write a narrative in your webpage explaining your cluster analysis and what you learned.

<!--
**IF using regression analysis** 

2. Perform a multivariate regression, copy and paste your regression output into your google site and briefly describe the results - interpret the coefficients and discuss overall model fit.
   
3. Use future predicted values for one of the variables in your regression analysis (e.g., population...) to forecast values of your outcome variable. 
  
4. Create and export a dataset that includes the actual and predicted values of this variable.

**IF using cluster analysis** 
-->

## Part 2: Tableau
<!--
1. **IF using regression analysis** Create TWO visualizations that shows the difference between the observed and future values of your outcome variable. 

1. **IF using cluster analysis** 
Create TWO visualizations that help you assign meaning to your clusters. 
-->

1. Create TWO visualizations that show your clusters, exploring the underlying meaning of your clusters by seeing how clusters compare across the variables you used to define them (create scatter plots to show this). Your analysis should include a description of the "meaning" of each cluster. For example, does one cluster indicate the areas that are more favorable to locate your store?

> Note: If the clusters you generated in R turn out to not be useful, you can use Tableau's clustering analysis to change the variables or number of clusters to find more useful groupings. 

2. Discuss take-aways for your research question based on your analysis. What did your analysis uncover?

## How to Submit

You should create a new webpage on your Google site titled `Project 2 Problem Set 3`. Parts 1 should include your annotated code, summary statistics from your cluster analysis, and the accompanying discussions. Part 2 should include your two data visualizations and a discussion of your findings. Submit the link to your Google site webpage in Canvas. 