---
title: "Project 00 (Problem Set 4): Mini Project"
format: 
  html:
    theme: zephyr
---

The objectives of the project are to:

- Integrate the R and Tableau skills that you have learned so far in the course 

- Analyze data with a question or insight in mind

- Communicate your insight through a webpage

## Prompt

You have been tasked as analysts to investigate trends in sales data from three branches spanning 2017 through 2019. The decision-maker wants to leverage data insights to inform better business decisions but has not provided specific direction.

Your role is to:

1. Conduct exploratory data analysis (EDA) to understand the dataset.
2. Identify a meaningful insight worth sharing with management.
3. Develop a compelling data story that effectively communicates your findings to the audience.

Once you find an insight, develop your [data story](https://csu-arec-330.github.io/materials/unit_00/week_04/lecture_00_week_04.html#/story-overview).


## R: Data Processing

Link to the description of the supermarket sales data available in the [Supermarket Sales Data Overview](https://csu-arec-330.github.io/materials/unit_00/inputs/supermarketdata_describe.html).

Using R, complete the following steps:

1. **Combine Datasets**. You are given sales data in three separate files (one for each year). Use R to append those datasets into a single dataset suitable for analysis and output it as a CSV file for Tableau.

2. **Handle Missing Data**. There was a problem integrating the E-wallet payment system data with the rest of the dataset.  The `gross_income` and `gross_margin_percentage` values are missing for transactions with E-wallet payments.  Use other information in the dataset to fill in the missing values (labeled as "NA") by calculating these fields.  *You can check your work by comparing your calculated values with those present in the dataset.*

3. **Export the Dataset**. Use R to write a csv file that your can read into Tableau.


## Tableau: Data Visualization

Using Tableau, create **at least three visualizations** to support your data story. The visualizations can be static or interactive but should adhere to the [guidelines for better data visualizations](../week_03/lecture_00_week_03.html#/guidelines-for-a-better-data-vis).

Visualization Requirements:

- Each visualization should highlight a specific aspect of your analysis.
- Be clear but informative while supporting your narrative effectively.


## Google Sites: Webpage Report

Present your analysis as a comprehensive webpage report. The webpage should:

1. **Narrative**: Include a written narrative of **500 to 750 words** that explains your analysis and insights. Examples of questions you might ask the data are:

- What are the sales trends over time? Are the patterns stable across branches/years?
- What products generate the most sales?  Which products yield the highest gross income? Does this vary by location?
- How is customer satisfaction trending?  Does this vary by location or product?

2. **Visualizations**: Embed Tableau visualizations to support your narrative. Be sure that they support a narrative consistent with the questions you are asking and answering.
<!-- - What is your insight?  use data visuals to explain why something is the way it is-->

3. **Data Story Elements**: The webpage should contain these elements:

- Question or compelling hook: What are you investigating?
- Characters and setting: Context of the sales data and branches.
- Preliminaries: Important observations or trends leading to your insight.
- Answer or insight: What is your main finding?
- Next steps: What can the manager/decision-maker do with this information? What recommendations do you have for further analysis?
- Limitations of analysis: What are the shortcomings of your analysis?  How might you alter your data collection processes to revisit your question in the future?

Remember: This report is being written for a management team, so be sure to write the report with this audience in mind.


## How to Submit

You should create a new webpage on your Google site titled `Unit 0 Mini Project`. This webpage should include a write up of your analysis including a brief description of any data processing steps. Generate a log file from your R code and submit that to Canvas. Submit the link to your Google site webpage in Canvas.

1. **Create a Webpage:**

- Title your webpage Unit 0 Mini Project.
- Include the following:
  - A write-up of your analysis with a brief description of the data processing steps. **Note: This should not be your R script. This should be a technical description of your analysis.**
  - Embedded Tableau visualizations.
  - Your narrative (500–750 words).
- On a separate page, titled Unit 0 Mini Project Appendix, include the R script used to generate your data file used to create your visualizations.

2. **Generate a Log File:**

- Use the `sink()` command in R to create a log file that demonstrates your script ran successfully.

**Alternative Process:**

*Given the truncation issues with generating log files, here is an alternative solution. Please use this method going forward.*

{{< video https://youtu.be/B2AchbhnFTo aspect-ratio="16x9" >}}

- Under the File menu, select **Compile Report...**
- The default under "Report output format" is HTML. 
- Select **Compile**
- Along the tool bar, select **Open in Browser**
- Hover your cursor over white space and **right click**.
- Select **View page source**.
- A new screen will appear with HTML code. (Don't worry, this might look like gibberish, but it's not!)
- Using your keyboard, click **`CTRL`+`A`**. This will highlight all of the HTML code.
- While the HTML code is highlighted, **right click** and select **Copy**.
- Go to your Google website. 
- Similar to as you would embed your Tableau visualization, select **Embed** under Insert.
- Then, select **Embed code**.
- Paste your embed code from your clipboard by either right-clicking and selecting **Paste** or `CTRL`+`V`.
- Select **Next**.
- **Resize** the image of your R script by expanding the window to fit the entire script.  

Following these steps will display your entire code and output without truncation. 

3. **Submit via Canvas:**

- Submit the link to your Google Site webpage in Canvas.

