---
title: "Unit 1: Final Project and Presentations"
format: 
  html:
    theme: zephyr
---

## Overview

The goal of this project is for you to apply the tools for time series analysis that we have covered in the course to answer a real world question. This is also a chance to showcase your creativity and analytical skills. Create something that you are proud to show others.

[**Rubric**](project_1_rubric.html)

### The Question

**The question** should be one related to agriculture, the environment, or natural resources and of interest to a business/company, a marketing board, policy makers, non-governmental organizations (NGO), or other nonprofit organizations. The question must be one that can be answered with time series data. For example:

- **Business:** Which commodity should I plant now to harvest in 5 years?

- **Marketing Board:** What marketing campaign should we run to to ensure that there is sufficient demand for the future production of strawberries?

- **Policy maker:** Which commodities should we consider subsidizing to ensure continued domestic production?

- **NGO/Nonprofit:** What is will demand be for electric cars in 5 years and what can we do to increase it?

### The Data

You will be responsible for collecting your own time series data to answer this question. Here are a few useful resources to help you in this process:

- [Economic data from the St. Louis Fed](https://fred.stlouisfed.org/tags/series)

- [USDA Ag Marketing Service Market News Data](https://www.ams.usda.gov/market-news)

- [US EPA Pollution Data](https://www.epa.gov/outdoor-air-quality-data/download-daily-data)

- [Statista](https://www.statista.com) - Database of thousands of statistics on a wide range of topics, including media, the environment, business and industry, sports, communication, health care and more. 

- [Gallup Analytics](https://www.gallup.com/analytics/318923/world-poll-public-datasets.aspx)

- [US Census Data](https://data.census.gov/profile?q=United+States&g=0100000US)

- [Kaggle](https://www.kaggle.com)

### The Analysis

Our expectation is that you will use time series data from any of the above sources in a forecasting exercise. The length of your forecast and the specific forecasting model you apply will depend on your research question and the underlying data. The only strict requirements are: 

0. Present summary statistics of your data. We recommend including: a visual analysis including a trend line and identification of structural breaks, and the mean, standard deviation, and range of values. 

1. Construct a decomposition-style forecast and estimate associated prediction intervals in R

2. Plot the decomposition, forecast, and prediction intervals in Tableau 

3. Discuss any assumptions you made in your analysis - did you account for structural breaks? Did you use your full time series? What model did you use and why? Did you need to interpolate any missing values in your data?

4. Identify limitations to your analysis (are you certain you are using the best forecasting method?)

5. Use the forecast to answer your research question

### The Presentation (80 points)

**Overall presentation expectations:** (20 points total)

Your presentations should be 6-9 minutes long. (5 points)

Your presentation should be engaging, follow a logical structure, and should tell a cohesive story that answers your stated question. (5 points)

Your visualizations should be well formatted and appropriate for your analysis/presentation (10 points)

**Presentation Introduction, Background, and Question:** (15 points total)

You should begin your presentation with the following: (5 points)

- Who are you? (what business, organization, etc. wants an answer to your question) 

- Who is your audience? (business executive team, policy makers, consumers?) 

You should then: 

- Give us any relevant background info that is necessary to understanding your question (as in my example...) (5 points)

- State your question (5 points - the question should be realistic (i.e., something a real world company would like an answer to), clearly stated, and answerable with a time series forecasting analysis)

**Presentation Data and Analysis:** (35 points total)

Data: 

- Describe where your data is from (5 points)

- Provide summary statistics and visualizations (10 points, see step 0 under [**Analysis**](https://csu-arec-330.github.io/materials/unit_01/week_03/ps7.html#the-analysis) above)

Analysis:

- What forecasting model did you use? (5 points)

- What assumptions did you make in your analysis?  What are limitations to your analysis? (5 points, see steps 3 and 4 under [**Analysis**](https://csu-arec-330.github.io/materials/unit_01/week_03/ps7.html#the-analysis) above)

- Plot and describe your decomposition, forecast, and prediction intervals in Tableau. (10 points)

**Presentation Discussion/Conclusion:** (10 points total)

- How did you use your forecast to answer your question? What is the answer to your question?

- What are the key take-aways for your intended audience?


### The Write-up/Online Submission (40 points)

You and your partner should also produce a written version of this analysis to post on your website. This should include all of the above components that went into your presentation (think of this as the report that you give to your audience to accompany your presentation) in addition to your R code. The written portion of the assignment is due later so that you can incorporate feedback that you receive during the oral presentation in class.

Because much of the presentation grade is tied to the content of your report, grading for the report will be based on: 

1. Is your code correct and well-explained? Use comments to explain what you do at each step! Produce an R log.txt file using the `sink()` command and include it as an appendix to your write up. (15 points)

2. Is your report readable and useful? We will not assess the quality of your research question, but we will assess whether your report is something you could hand out to your intended audience and have them understand what you did, why you did it, and what they should do with the information. (15 points)

3. Organization, formatting and structure. Is your report organized, presented in a logical order, with appropriate integration of writing, analysis, and code? (10 points)

